FROM node:22-alpine AS build
RUN apk add --no-cache ffmpeg python3 py3-pip espeak-ng font-noto-bengali
WORKDIR /app
COPY . .
RUN npm ci --no-audit --no-fund
RUN npm run build

FROM node:22-alpine
RUN apk add --no-cache ffmpeg python3 py3-pip espeak-ng font-noto-bengali
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
CMD ["node", "apps/worker/dist/index.js"]
