FROM node:22-alpine AS build
RUN apk add --no-cache ffmpeg python3
WORKDIR /app
COPY . .
RUN npm ci --no-audit --no-fund
RUN npm run build

FROM node:22-alpine
RUN apk add --no-cache ffmpeg python3 font-noto-bengali
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 4000
CMD ["node", "apps/api/dist/index.js"]
